### ISSUE TITLE
Error  while installing

### ISSUE THREAD

**Issue by RoiBenDavid** [bestK1ngArthur/homebridge-mihome#3]
hoobs@hoobs:/var/lib/homebridge $ npm install -g git+https://github.com/bestK1ngArthur/homebridge-mihome

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/bestK1ngArthur/homebridge-mihome.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-01-24T21_21_13_635Z-debug.log
hoobs@hoobs:/var/lib/homebridge $ 
hoobs@hoobs:/var/lib/homebridge $

**Comment by RoiBenDavid** [comment]
![](https://i.ibb.co/6nd5DNL/Screen-Shot-2021-01-24-at-23-21-21.png)

**Comment by bestK1ngArthur** [comment]
Hi, maybe the git is not installed on your machine. Try running `git --version`
